# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Ena Ibeh
description: "Hi I'm Ena, and I'm a Data Analyst with an environmental and efficiency background based in New York, NY. I want to provide organizational value through data-informed analytics and visualization within the environmental and sustainability field, preferably. Connect with me on LinkedIn for inquiries."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#add8e6"> Portfolio </span>
location: "New York, NY"
resume_url: /docs/Ena Ibeh_ Data Analyst_RESUME.pdf
avatar_image: /img/Ena_Ibeh.jpg

#------------------------------- 
# Contact links
linkedln: "https://www.linkedin.com/in/ena-ibeh/" # Add your linkedln handle
github: "https://github.com/EnaNYC"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

